app/models/User.py
from . import db
from flask_login import AnonymousUserMixin, UserMixin
from sqlalchemy import func
from werkzeug.security import generate_password_hash as gph
from config import SALT


class User(db.Model, UserMixin):
    __tablename__ = "users"

    id = db.Column(db.Integer, autoincrement=True, primary_key=True)
    name = db.Column(db.String(50), nullable=True, unique=False, default="")
    surname = db.Column(db.String(50), nullable=True, unique=False, default="")
    username = db.Column(db.String(50), nullable=False, unique=True)
    email = db.Column(db.String(50), nullable=True, unique=True)
    password = db.Column(db.String(130), nullable=False, unique=False)
    img_profile = db.Column(db.String(256), nullable=True, default="")

    @property
    def serialize(self):
        return {"username": self.username, "email": self.email}

    @staticmethod
    def create(username, password, email="", name="", surname=""):
        new_user = User(
            username=username,
            email=email,
            password=gph(password + SALT),
            name=name,
            surname=surname,
        )

        db.session.add(new_user)
        db.session.commit()

    @staticmethod
    def get_users():
        return [
            {
                "id": user.id,
                "username": user.username,
                "name": (user.name + " " + user.surname),
                "email": user.email,
            }
            for user in User.query.order_by("id").all()
        ]

app/models/__init__.py
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
login_manager = LoginManager()

from . import User

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[
                           DataRequired("Por favor, preencha aqui")])
    password = PasswordField('Password', validators=[
                             DataRequired("Por favor, preencha aqui")])
    remember_me = BooleanField('Lembrar de mim')
    submit = SubmitField('Entrar')


class ContatoForm(FlaskForm):
    email = StringField('Email', validators=[
                        DataRequired("Por favor, preencha aqui")])
    text = TextAreaField('Text', description="Escreva algo para nós! :)", validators=[
                         DataRequired("Por favor, preencha aqui")])
    submit = SubmitField('Enviar')

app/__init__.py
import os
import sys

sys.path.append(os.path.abspath(os.path.dirname(__file__)))

app/app.py
from flask import Flask
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap5
from flask_wtf import CSRFProtect
from config import ROOT_PATH, DEBUG
from models import db
from routes import register_blueprints

app = Flask(__name__, static_url_path=ROOT_PATH + "/static")
app.config.from_object("config")
db.init_app(app)
bootstap = Bootstrap5(app)
csrf = CSRFProtect(app)
migrate = Migrate(app, db)

register_blueprints(app)

if __name__ == "__main__":
    app.debug = DEBUG
    app.run(host="0.0.0.0")

app/controllers/home.py
from flask import render_template


def index():
    user = {"username": "Melissa"}
    posts = [
        {
            "author": "Felipe",
            "text": "Aprendendo Python Flask, um microframework para criar webapp",
            "date": "22/01/2023",
        },
        {
            "author": "Melissa",
            "text": "Visitando hospital na aula de hoje!",
            "date": "20/01/2023",
        },
        {"author": "Flávio", "text": "Primeiro dia de aula", "date": "1 ano atrás"},
    ]

    return render_template("index.html", title="home page", user=user, posts=posts)


def about():
    description = None

    return render_template("about.html", description=description)

app/controllers/user.py
from app import app
from flask import render_template
from app.forms import LoginForm


def login():
    form = LoginForm()

    return render_template("login.html", title="Logar", form=form)

app/routes/__init__.py
from flask import g
from app.config import ROOT_PATH, ALLOWED_EXTENSIONS

from routes.home_rt import home_rt
from routes.user_rt import user_rt

modules = {
    ROOT_PATH + "/": home_rt,
    ROOT_PATH + "/login": user_rt,
}


def load_config():
    g.valid_file_extensions = ALLOWED_EXTENSIONS
    g.root_path = ROOT_PATH


def register_blueprints(app):
    for url, module in modules.items():
        app.register_blueprint(module, url_prefix=url)

app/routes/home_rt.py
from crypt import methods
from flask import Blueprint

from controllers.home import index
from controllers.home import about


home_rt = Blueprint("home", __name__)

home_rt.route("/", methods=["GET"])(index)
home_rt.route("/about", methods=["GET"])(about)

app/routes/user_rt.py
from flask import Blueprint

from controllers.user import login

user_rt = Blueprint("user", __name__)

user_rt.route("/login", methods=["GET", "POST"])(login)

app/templates/about.html
{% extends "base.html" %}

{% block content %}

<div class="simpl_block" style="margin: 100px 400px 100px 400px; text-align: center;">
    {% if description %}
    <p>{{ description }}</p>
    {% else %}
    <p> 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac eros et tellus malesuada blandit. 
        Sed maximus purus ac ultrices lacinia. Etiam venenatis est orci, a pellentesque augue volutpat vitae. 
        Praesent euismod aliquam orci, scelerisque hendrerit est accumsan vel. Vestibulum eget faucibus felis. 
        Aenean leo felis, congue sed dolor non, molestie rutrum dui. Fusce finibus lorem vitae sagittis scelerisque. 
        Aenean ut ultricies libero, et pulvinar diam. Vestibulum laoreet suscipit magna. Maecenas vel lorem aliquam, 
        pretium elit vel, dignissim libero. Suspendisse porttitor rhoncus tellus et laoreet. Nunc sed tortor rutrum, 
        molestie eros eget, consequat sapien. Proin non rutrum diam. Quisque posuere ac ipsum sit amet efficitur. 
        Aliquam mattis nunc non sem malesuada, id lobortis risus hendrerit.
        Donec at ligula risus. Aenean iaculis tortor ac neque egestas hendrerit. Proin eget magna vitae libero auctor 
        maximus. Vestibulum dictum leo nec nulla iaculis dapibus. Praesent varius dictum leo, placerat laoreet ipsum 
        dignissim non. Nulla ex ante, luctus ac rhoncus sit amet, ultrices nec risus. Nam nec feugiat lorem. In urna 
        lacus, accumsan id placerat non, finibus sed turpis. Cras non sodales mi, id egestas velit. Sed ex diam, bibendum 
        sit amet augue in, porta euismod nulla. Fusce tincidunt lectus finibus mi ultricies ornare. Class aptent taciti 
        sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam commodo tortor sit amet sollicitudin 
        molestie. Etiam mattis at ipsum id condimentum. Duis eu lobortis eros, non egestas arcu. Maecenas interdum suscipit 
        blandit.        
        Nullam non sapien ut sem rhoncus semper. Aliquam hendrerit semper metus, ac tristique diam scelerisque vitae. 
        Nam vehicula lorem non erat tincidunt, eu feugiat purus sodales. Vestibulum convallis consequat semper. 
        Pellentesque arcu eros, consectetur consequat hendrerit vel, imperdiet et magna. Proin non nisl mauris. Proin sit 
        amet velit at tortor ultricies sollicitudin quis in orci. Ut vel risus et nibh mollis accumsan. Donec a sapien nec 
        velit molestie ultrices nec a sem. Proin vitae consequat massa. Sed fringilla sed eros vel sagittis. Curabitur risus 
        ipsum, auctor ut nunc sed, placerat convallis sem. Vestibulum ullamcorper malesuada ante ut finibus. Vestibulum 
        lacinia, urna eget pharetra commodo, sapien justo accumsan augue, id feugiat neque lacus id lorem.
    </p>
    {% endif %}
</div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>

    <head>
        {% if title %}
        <title>{{title}} - Microblog</title>
        {% else %}
        <title>Welcome to Microblog</title>
        {% endif %}

        <style>
            .simpl_block {
                background-color: rgb(180, 120, 236);
                border-radius: 5px;
                border-width: 2px;
                border: solid;
                margin: 10px 900px 5px 20px;
                padding: 5px;
                text-align: justify;
            }
        </style>
    </head>

    <body style="background-color: rgb(191, 186, 196)">
        <b>
            <div>Microblog: <a href="{{ url_for('home.index') }}">Home</a> |
                <a href="{{ url_for('user.login') }}">Login</a> |
                <a href="{{ url_for('home.about') }}">Sobre</a>
            </div>
        </b>
        <hr>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}

<h1>Hello, {{user.username}}!</h1>
<div class="simpl_block">
    {% for p in posts %}
    <div>
        <p>{{ p.author }}: <b>{{ p.text }}</b><br>
            <span style="font-size: x-small;">{{ p.date }}</span>
        </p>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}

<div class="simpl_block">
    <h1>Logar</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span><br>
            {% endfor %}
            {{ form.username.label }}<br>
            {{ form.username(size = 32) }}
        </p>
        <p>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span><br>
            {% endfor %}
            {{ form.password.label }}<br>
            {{ form.password(size = 32) }}
        </p>
        <p> {{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p> {{ form.submit() }}</p>
    </form>
</div>

{% endblock %}